# Who is this?
title: زال
tagline: آگاهی از ناتوانی‌های شناختی در سالمندی
description: >-
  آگاهی از ناتوانی‌های شناختی در سالمندی
locale: fa-IR
direction: rtl
baseurl: ""
url: https://joinzal.ir
logo: 
  light: /assets/img/logos/zal-color-light.png
  og: /assets/img/logos/zal-color-light-og.png
authors:
  - name: Kiarash Azimzadeh
  - url: https://www.linkedin.com/in/kiarashazimzadeh/

# Site configuration
permalink: /:categories/:title

defaults:
  -
    scope:
      path:            "assets"
    values:
      sitemap:         false

# Build settings
plugins:
  - jekyll-compose
  - jekyll-sitemap
  - jekyll-jalali

# Exclusion
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - yarn.lock
  - package.json
  - package-lock.json
  - LICENSE
  - README.md

# Sass configuration
sass:
  load_paths:
    - _sass
    - node_modules

# Plugins configuration
jekyll_compose:
  default_front_matter:
    # posts:
    #   layout: single
    #   language: fa-IR
    #   aside: true
    # promotions:
    #   layout: single
    #   language: fa-IR
    #   color: primary
    heroes:
      layout: single
      language: fa-IR
      bg-color: primary

# Collections
collections:
  promotions:
    output: true
  projects:
    output: true
  heroes: