# Who is this?
title: زال
description: >-
  آگاهی از ناتوانی‌های شناختی در سالمندی
locale: fa-IR
direction: rtl
baseurl: ""
url: "https://joinzal.ir"
logo: 
  color: "assets/img/logo-color-light.png"
  bw: "assets/img/logo-bw-light.png"
authors:
  - name: "Kiarash Azimzadeh"

# Site configuration
permalink: /:categories/:title

# Build settings
plugins:
  - jekyll-compose
  - jekyll-jalali

# Exclusion
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - yarn.lock
  - package.json
  - package-lock.json
  - LICENSE
  - README.md

# Sass configuration
sass:
  load_paths:
    - _sass
    - node_modules

# Plugins configuration
jekyll_compose:
  default_front_matter:
    # posts:
    #   layout: single
    #   language: fa-IR
    #   aside: true
    # promotions:
    #   layout: single
    #   language: fa-IR
    #   color: primary
    heroes:
      layout: single
      language: fa-IR
      bg-color: primary

# Collections
collections:
  promotions:
    output: true
  heroes: