# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: زال
description: >-
  آگاهی از ناتوانی‌های شناختی در سالمندی
locale: fa-IR
direction: rtl
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kiarashazimzadeh.github.io/zal-site" # the base hostname & protocol for your site, e.g. http://example.com
logo: 
  color: "assets/img/logo-color-light.png"
  bw: "assets/img/logo-bw-light.png"

# Site configuration
permalink: /:categories/:title

# Build settings
plugins:
  - jekyll-compose

# Exclusion
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - yarn.lock
  - package.json
  - package-lock.json
  - LICENSE
  - README.md

# Sass configuration
sass:
  load_paths:
    - _sass
    - node_modules

# Plugins configuration
jekyll_compose:
  default_front_matter:
    posts:
      layout: single
      language: fa-IR
      toc: true
    promotions:
      layout: single
      language: fa-IR
      color: primary
      ext-link: false

# Collections
collections:
  promotions:
    output: true