name: RTLCSS

on:
  push:
    branches: 
      - gh-pages

jobs:
  rtlcss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g rtlcss
      - run: rtlcss css/style.css css/style.css
        working-directory: assets

